import React, { useEffect, useState } from 'react';
import './Home.css';
import logo from './assets/dalltoon-logo.png'; // Import the logo image
import { useNavigate } from 'react-router-dom'; // useNavigate 훅 임포트

const Home = () => {
  const [comics, setComics] = useState([]);
  const navigate = useNavigate(); // useNavigate 훅 사용

  useEffect(() => {
    const fetchComics = async () => {
      try {
        const response = await fetch('http://localhost:8080/api/comics/all');
        const comicsData = await response.json();

        // Fetch first scene for each comic
        const comicsWithThumbnails = await Promise.all(
          comicsData.map(async (comic) => {
            const sceneResponse = await fetch(
              `http://localhost:8080/api/comics/${comic.id}/firstScene`
            );
            const firstScene = await sceneResponse.json();
            return {
              ...comic,
              thumbnailUrl: firstScene ? firstScene.imageUrl : null,
            };
          })
        );

        setComics(comicsWithThumbnails);
      } catch (error) {
        console.error('Error fetching comics:', error);
      }
    };

    fetchComics();
  }, []);

  const handleLogout = () => {
    // Add your logout logic here
    console.log('Logout');
  };

  const handleCreateComic = () => {
    navigate('/create'); // "/create" 페이지로 리다이렉트
  };

  return (
    <div className="home-container">
      <div className="navbar">
        <div className="navbar-links">
          <a href="#comics">Comics</a>
          <a href="#create" onClick={handleCreateComic}>
            Create Own Comic
          </a>
          <a href="#best">Best Comic</a>
        </div>
        <button className="logout-button" onClick={handleLogout}>
          Logout
        </button>
      </div>
      <div className="intro-section">
        <img src={logo} alt="Dalltoon Logo" className="logo" />
        <div className="description">
          <h1>Welcome to Dalltoon</h1>
          <p>
            Dalltoon is an innovative and creative platform designed for
            artists, storytellers, and anyone with a passion for comics. Our
            unique service leverages the power of DALL-E, an advanced AI model
            developed by OpenAI, to generate high-quality images based on your
            textual descriptions. Whether you are a professional comic artist or
            an enthusiastic beginner, Dalltoon provides you with the tools to
            bring your stories to life in a visually compelling way. Imagine
            being able to create a comic strip where each scene is dynamically
            generated by AI, capturing the exact essence of your imagination.
            Dalltoon allows you to describe your scenes in detail, and within
            moments, you'll have beautifully crafted images ready to be
            assembled into your comic. This not only saves countless hours of
            manual drawing but also opens up new possibilities for creativity
            and experimentation. Our platform is user-friendly and intuitive,
            designed to make the process of creating comics as seamless as
            possible. Simply enter your scene descriptions, and let Dalltoon do
            the rest. You can edit, rearrange, and finalize your comic with
            ease. Additionally, Dalltoon supports a collaborative environment,
            allowing multiple users to work on a comic project together, making
            it perfect for team projects and educational purposes. At Dalltoon,
            we believe that everyone has a story to tell, and we are committed
            to helping you tell yours in the most engaging way possible. Join us
            today and start creating comics that captivate and inspire.
          </p>
        </div>
      </div>
      <div className="comics-list">
        {comics.map((comic) => (
          <div key={comic.id} className="comic-item">
            <div className="thumbnail-container">
              <img
                src={comic.thumbnailUrl}
                alt={`${comic.title} thumbnail`}
                className="thumbnail"
              />
            </div>
            <h2>{comic.title}</h2>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
